[tool.poetry]
name = "weather-station"
version = "0.1.0"
description = ""
authors = ["Jordan McVeigh <jordan.mcveigh@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
influxdb-client = "^1.45.0"
weatherhat = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
